### ISSUE TITLE
[Feature] Default category

### ISSUE THREAD

**Issue by whitespots** [Whitespots-OU/security-requirements-generator#10]
So called "default category"

It shout be always added to the requirements list if it is checked as default in admin panel.

**Comment by stateandprove** [comment]
Added. In admin panel it's possible to add default categories and default requirements for them: for each default category admin can set default requirements. Chosen categories and corresponding requirements are added in the generated pdf even if user didn't choose them. If no default categories are set then no default requirements are applied for categories chosen by the user. 

For example:

1) We want "admin actions" category to be invisible at the home page but also want it to be added in the pdf file. We also want the "search engine indexation" category to be visible for a user, but still to be default, i.e. it's added in the pdf no matter if user chose it or not. 

![default_cat](https://user-images.githubusercontent.com/80955529/125367462-d98abf80-e380-11eb-883d-b7bec8666496.jpg)

2) For the above default categories, we choose some default requirements. Those default requirements will be marked as important, but ONLY for default catogories, not for ones chosen by user.

![default_cat1](https://user-images.githubusercontent.com/80955529/125367478-df80a080-e380-11eb-92f3-1bdd02b07e55.jpg)

3) So, this set of settings

![default_cat2](https://user-images.githubusercontent.com/80955529/125367486-e3142780-e380-11eb-9307-f248ea243fab.jpg)

4) Results in this pdf

![default_cat3](https://user-images.githubusercontent.com/80955529/125367488-e4455480-e380-11eb-841a-e9beeca56200.jpg)

Default categories are always placed above others.

**Comment by whitespots** [comment]
Done
