### ISSUE TITLE
[Issue] "Show at home" doesn't work

### ISSUE THREAD

**Issue by whitespots** [Whitespots-OU/security-requirements-generator#11]
Admin feature "show at home" does not work

**Comment by stateandprove** [comment]
It's fixed, now it works. In admin admin panel you can set "show_at_home" parameter for each category. For example, in the image below a category "admin actions" is not displayed on the home page.

![show_at_home](https://user-images.githubusercontent.com/80955529/125357171-ee128c00-e36f-11eb-800d-54a489ab7cc3.jpg)

**Comment by whitespots** [comment]
Done
