### ISSUE TITLE
[Issue] 500 when search for requirement in admin panel

### ISSUE THREAD

**Issue by whitespots** [Whitespots-OU/security-requirements-generator#12]

**Comment by W0uldYk1ndlY** [comment]
Search bar at pages:

- /admin/requirement/category/
- /admin/requirement/requirement/
- /admin/requirement/testcase/

 in admin interface works bad. 

At pages /admin/requirement/category/ and /admin/requirement/testcase/ search works very strange. 
At page /admin/requirement/requirement/ when you try to use search you get 500 error code:

![image](https://user-images.githubusercontent.com/86364646/124119951-d556cc00-da7b-11eb-8305-bd865a747ebd.png)

**Comment by stateandprove** [comment]
The 500 error at "/admin/requirement/requirement/" page is fixed. At two other pages (as well as at the former), any characters in the search field will be matched with characters (but not the full name) in the "tittle" or "name" field of a corresponding parameter.

![search](https://user-images.githubusercontent.com/80955529/125360182-27e59180-e374-11eb-81e5-e4c26a7eeb12.jpg)
![search1](https://user-images.githubusercontent.com/80955529/125360425-814dc080-e374-11eb-918a-cf93c108cbf2.jpg)

**Comment by whitespots** [comment]
Done
