### ISSUE TITLE
[Issue][Front] too small scrolling window

### ISSUE THREAD

**Issue by whitespots** [Whitespots-OU/security-requirements-generator#13]

**Comment by W0uldYk1ndlY** [comment]
Screenshot of a issue:

![image](https://user-images.githubusercontent.com/86364646/124122116-66c73d80-da7e-11eb-8d1b-9dd7c4ef4ce4.png)

**Comment by stateandprove** [comment]
For large screens, the maximum height is increased by 250px.

![issue-small-window](https://user-images.githubusercontent.com/80955529/125355348-9541f400-e36d-11eb-8069-ccd11c182354.jpg)

**Comment by whitespots** [comment]
Done
