### ISSUE TITLE
[Feature] Security assessment button should be edited

### ISSUE THREAD

**Issue by whitespots** [Whitespots-OU/security-requirements-generator#14]
Use case:
Any product owner should have a contact of security team. It might be a link to the slack channel/confluence page/whatever.
So, our idea is to give an opportunity to the corporate admin to edit such data.

Target state:
- Admin can change a value of the "Security assessment" button 
- Admin can change a link of this button should be editable in admin panel

**Comment by stateandprove** [comment]
Added. Now the admin can set value and link of the button. It may be done via the "common" section of an admin panel.

![button](https://user-images.githubusercontent.com/80955529/125360944-4a2bdf00-e375-11eb-8a42-f508f01c835d.jpg)
![button1](https://user-images.githubusercontent.com/80955529/125360950-4dbf6600-e375-11eb-98f4-b06df0724a26.jpg)

**Comment by whitespots** [comment]
Done
