### ISSUE TITLE
[Feature] Add City-mobil logo to readme, main page and export file 

### ISSUE THREAD

**Issue by W0uldYk1ndlY** [Whitespots-OU/security-requirements-generator#15]
Logo:

![image](https://user-images.githubusercontent.com/86364646/124122455-c7ef1100-da7e-11eb-836d-98b0cee081f7.png)

**Comment by stateandprove** [comment]
You can add other logos (max height 50px) via admin panel (common -> additional logos). Those logos marked as enabled are visible and placed next to the Whitespots logo.

![logo](https://user-images.githubusercontent.com/80955529/125361888-a80cf680-e376-11eb-9108-ae8489e34aa4.jpg)
![logo1](https://user-images.githubusercontent.com/80955529/125361891-a93e2380-e376-11eb-8028-e44ecb9b0252.jpg)

**Comment by whitespots** [comment]
Done
